### ISSUE TITLE
Add set/get params for all primitives. 

### ISSUE THREAD

**Issue by BalazsHoranyi** [uncharted-distil/distil-primitives#119]
- [x] audio_reader.py
- [x] audio_transfer.py
- [x] bert_classifier.py
- [x] binary_encoder.py
- [x] categorical_imputer.py
- [x] collaborative_filtering_link_prediction.py
- [x] community_detection.py
- [x] enrich_dates.py
- [x] ensemble_forest.py
- [x] image_transfer.py
- [x] k_means.py
- [x] link_prediction.py
- [x] list_to_dataframe.py
- [x] load_edgelist.py
- [x] load_graphs.py
- [x] load_single_graph.py
- [x] mi_ranking.py
- [x] one_hot_encoder.py
- [x] output_dataframe.py
- [x] prediction_expansion.py
- [x] replace_singletons.py
- [x] satellite_image_loader.py
- [x] seeded_graph_matching.py
- [x] text_classifier.py
- [x] text_encoder.py
- [x] time_series_formatter.py
- [x] vertex_nomination.py

**Comment by cdbethune** [comment]
Fixed by #122 #123 #124 #125 #128
