### ISSUE TITLE
Test with torch 1.7.0

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-primitives#247]
JPL is working on a primitive that needs torch 1.7.0.  Our primitives are on 1.4.0, and they wanted to know if we could bump our version.  We should bump and re-test to see if the update causes any problems.

**Comment by venkatkorapaty** [comment]
All of our primitives and models (except for fixed_cnn) work with torch==1.7.

Couldn't test fixed_cnn as we have no primitives that uses it.
