### ISSUE TITLE
Ensure graph problems produce predictions as integers

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-primitives#29]
We got scores of zero for `49_facebook` (graph matching), and `59_umls` (link prediction) from the d3m core scoring utilities.  The only difference between our predictions and the ones that are in the solution in the dataset itself is that ours are floats `0.0` and `1.0`, and the solution is ints `0` and `1`.  My guess is the scoring code treats things as categoricals because of the metric and thus matches on the value as strings.

**Comment by nowfred** [comment]
https://github.com/uncharted-distil/distil-primitives/commit/57808e079ff81f12b2d5fa422ecfa2618631f163
