### ISSUE TITLE
Verify community detection primitive

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-primitives#64]
Current version is just the null model.  We should check with @bkj to see If there wasn't a more complete implementation available as part of the exline work.

**Comment by cdbethune** [comment]
The current D3M community detection problems are all defined such that the null model provides the best scores, so Exline didn't include a full implementation of a community detection primitive. 
@slangevi  : @bkj has said that he can put together a community detection implementation if we want a general solution to the problem, or we can just pick up one of the existing primitives from the program to use moving forward.  Thoughts?

**Comment by BalazsHoranyi** [comment]
Looks like SRI has a community detection pipeline (https://gitlab.com/daraghhartnett/sri_d3m/blob/master/sri/psl/community_detection.py)  I can work on integrating that one

**Comment by cdbethune** [comment]
Okay.  I'm just going to get rid of this primitive since having to submit it is extra work.
