### ISSUE TITLE
lapjv requires cython

### ISSUE THREAD

**Issue by mitar** [uncharted-distil/distil-primitives#84]
It seems your primitives require lapjv, which requires cython. But that primitive seems to not declare such dependency. See error here (search for `lapjv`):

https://gitlab.com/datadrivendiscovery/images/-/jobs/395447551

**Comment by BalazsHoranyi** [comment]
fixed via https://github.com/uncharted-distil/distil-primitives/pull/88

**Comment by mitar** [comment]
That is not correct. Cython has to be installed even before `setup.py` is run. You have to add it as primitive dependency, not package dependency. I think you have in your group some existing primitives which require that.

**Comment by mitar** [comment]
Or not cython, but something similar. See: https://github.com/uncharted-distil/distil-primitives/issues/31

**Comment by BalazsHoranyi** [comment]
oh, gotcha. Sorry about that. I believe this should work. https://github.com/uncharted-distil/distil-primitives/pull/90
